export var mapConfig = {

  //ESRI Vector BaseMap
  ESRIVectorBasemap: {
    name: "DarkGray"
  },

  //tile layers (WMS)
  TMSLayers:[
    {
      id: "CONUS_HubsTMS",
      layer: "Hubs TMS",
      label: "Resilience Hubs",
      apikey: 'hubs',
      hubsapikey: 'hubs',
      chartLabel: 'Resilience Hubs',
      chartLegendValues: 10,
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#ffc500',
        2: '#f9b500',
        3: '#f3a400',
        4: '#ed9400',
        5: '#e78300',
        6: '#e07000',
        7: '#d95e00',
        8: '#d14c00',
        9: '#ca3600',
        10: '#c21500',
      },
      chartDriver: false,
      chartSummary: true,
      chartOrder: 1,
      chartInputName: 'summary',
      chartInpuLabel: 'Summary',
      chartCSSSelector: 'hubs',
      chartMaxValue: 11,
      chartMinValue: 0,
      chartScale: 0,
      chartScaleGroups: 1,
      chartNoDataOverRide: 1,
      url: "https://tiles.resilientcoasts.org/HubsIndexTiles/{z}/{x}/{y}.png",
      attribution: "NFWF 2018",
      format: "image/png",
      tileSize: 256,
      transparent: true,
      opacity: 0.75,
      zIndex: 9000,
      crs: L.CRS.EPSG3857,
      maxNativeZoom: 13,
      tms: false,
      legend: "hub",
      description: "Areas of open lands and protected space that are most suitable for resilience-building efforts. Hubs are ranked by priority, given the level of exposure that nearby assets have to flood-related threats and the presence and abundance of fish and wildlife species within and surrounding the Hub.",
      source: 'regional',
      region: 'continental_us'
    },
  ],

  //tile layers (WMS)
  WMSLayers:[
    {
      id: "southeast_swir_threshold",
      layer: "southeast-swir-currentMaskForForestCloudGap",
      label: "SWIR Differencing (Threshold)",
      url: "http://landsatfact-data.nemac.org/lsf-swir-threshold?",
      attribution: "SouthFACT 2018",
      format: "image/png",
      tileSize: 256,
      transparent: true,
      opacity: 0.75,
      zIndex: 9000,
      crs: L.CRS.EPSG900913,
      legend: "southeast_swir_threshold",
      description: "",
      apikey: 'southeast_swir_threshold',
      hubsapikey: 'southeast_swir_threshold',
      chartLabel: 'SWIR Differencing (Threshold)',
      chartLegendValues: 15,
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#ffc500',
        2: '#f9b500',
        3: '#f3a400',
        4: '#ed9400',
        5: '#e78300',
        6: '#e07000',
        7: '#d95e00',
        8: '#d14c00',
        9: '#ca3600',
        10: '#c21500',
        11: '#d95e00',
        12: '#d14c00',
        13: '#ca3600',
        14: '#c21500',
        15: '#c21500'
      },
      chartDriver: false,
      chartSummary: true,
      chartOrder: 1,
      chartInputName: 'summary',
      chartInpuLabel: 'Summary',
      chartCSSSelector: 'southeast_swir_threshold',
      chartMaxValue: 16,
      chartMinValue: 0,
      chartScale: 0,
      chartScaleGroups: 1,
      source: 'regional',
      region: 'southeast'
    },
    {
      id: "southeast_swir_threshold_all",
      layer: "southeast-swir-currentMaskForForestCloudGap",
      label: "SWIR Differencing (All Change)",
      url: "http://landsatfact-data.nemac.org/lsf-swir-allchange?",
      attribution: "SouthFACT 2018",
      format: "image/png",
      tileSize: 256,
      transparent: true,
      opacity: 0.75,
      zIndex: 9000,
      crs: L.CRS.EPSG900913,
      legend: "southeast_swir_threshold_all",
      description: "",
      apikey: 'southeast_swir_threshold_all',
      hubsapikey: 'southeast_swir_threshold_all',
      chartLabel: 'SWIR Differencing (All Change)',
      chartLegendValues: 10,
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#ffc500',
        2: '#f9b500',
        3: '#f3a400',
        4: '#ed9400',
        5: '#e78300',
        6: '#e07000',
        7: '#d95e00',
        8: '#d14c00',
        9: '#ca3600',
        10: '#c21500',
      },
      chartDriver: false,
      chartSummary: true,
      chartOrder: 2,
      chartInputName: 'summary',
      chartInpuLabel: 'Summary',
      chartCSSSelector: 'southeast_swir_threshold_all',
      chartMaxValue: 11,
      chartMinValue: 0,
      chartScale: 0,
      chartScaleGroups: 1,
      source: 'regional',
      region: 'southeast'
    },
    {
      id: "southeast_ndvi_current",
      layer: "southeast-ndvi-currentMaskForForestCloudGap",
      label: "NDVI",
      url: "http://landsatfact-data.nemac.org/lsf-NDVI?",
      attribution: "SouthFACT 2018",
      format: "image/png",
      tileSize: 256,
      transparent: true,
      opacity: 0.75,
      zIndex: 9000,
      crs: L.CRS.EPSG900913,
      legend: "southeast_ndvi_current",
      description: "",
      apikey: 'southeast_ndvi_current',
      hubsapikey: 'southeast_ndvi_current',
      chartLabel: 'NDVI',
      chartLegendValues: 10,
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#ffc500',
        2: '#f9b500',
        3: '#f3a400',
        4: '#ed9400',
        5: '#e78300',
        6: '#e07000',
        7: '#d95e00',
        8: '#d14c00',
        9: '#ca3600',
        10: '#c21500',
      },
      chartDriver: false,
      chartSummary: true,
      chartOrder: 3,
      chartInputName: 'summary',
      chartInpuLabel: 'Summary',
      chartCSSSelector: 'southeast_ndvi_current',
      chartMaxValue: 11,
      chartMinValue: 0,
      chartScale: 0,
      chartScaleGroups: 1,
      source: 'regional',
      region: 'southeast'
    },
    {
      id: "southeast_ndmi_current",
      layer: "southeast-ndmi-currentMaskForForestCloudGap",
      label: "NDMI",
      url: "http://landsatfact-data.nemac.org/lsf-NDMI?",
      attribution: "SouthFACT 2018",
      format: "image/png",
      tileSize: 256,
      transparent: true,
      opacity: 0.75,
      zIndex: 9000,
      crs: L.CRS.EPSG900913,
      legend: "southeast_ndmi_current",
      description: "",
      apikey: 'southeast_ndmi_current',
      hubsapikey: 'southeast_ndmi_current',
      chartLabel: 'NDMI',
      chartLegendValues: 10,
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#ffc500',
        2: '#f9b500',
        3: '#f3a400',
        4: '#ed9400',
        5: '#e78300',
        6: '#e07000',
        7: '#d95e00',
        8: '#d14c00',
        9: '#ca3600',
        10: '#c21500',
      },
      chartDriver: false,
      chartSummary: true,
      chartOrder: 4,
      chartInputName: 'summary',
      chartInpuLabel: 'Summary',
      chartCSSSelector: 'southeast_ndmi_current',
      chartMaxValue: 11,
      chartMinValue: 0,
      chartScale: 0,
      chartScaleGroups: 1,
      source: 'regional',
      region: 'southeast'
    },
 ],

 zoomRegions: [
   {
     region: 'southeast',
     label: 'Southeast U.S',
     center: [ 40.979898, -81.474609 ], // update
     extent: [ -132.97, 25.16, -62.49, 50.00], // update
     zoom: 4
   },
 ],

 mapDefaults: {
    center: [ 36.914764288955936, -82.33154296875001],
    zoom: 5,
 },

  //leaflet optoins expand as needed
  mapOptions: {
    // center: [ 32.7765, -79.9311 ],
    zoom: 4,
    maxZoom: 16,
    minZoom: 4,
    crs: L.CRS.EPSG3857
  }

};

export default mapConfig;
